### ISSUE TITLE
Rename to `better-canvas`

### ISSUE THREAD

**Issue by AngeloCore** [Brooooooklyn/canvas#614]
The name is [available](https://www.npmjs.com/package/better-canvas).
This will also help other developers to find the package more easily.

**Comment by skdhg** [comment]
While it is a good point, doing this can negatively impact all the dependents of this package

![image](https://user-images.githubusercontent.com/46562212/218329828-91661110-0130-4e14-a0e9-a429b051a151.png)

**Comment by AngeloCore** [comment]
The current package can be deprecated and a new package with a new name can be created.
A warning can also be added that the name of the old package is being changed.

**Comment by skdhg** [comment]
It may work for some projects out there but have you thought about dependents tree?

**Comment by AngeloCore** [comment]
The dependents won't stop working. They'll just get a warning if they update to the latest version.

**Comment by kyranet** [comment]
Having a package named `better-*` benefits nobody. Something being better or worse is almost never objective, and in this case, each Canvas package has its upsides and downsides, which makes somebody have to pick one among the three, and the more that will come in the future.

That being said, the definition of "better" depends on who you ask. For some people, "better" means one of "faster", "more featureful", "more stable", or "uses less resources". This package is currently the fastest, and has a lot of features, but `canvas` is the most stable, and `skia-canvas` has the largest feature set.

That is to say, there could easily be a Canvas engine that adopts zero-allocation strategies to avoid using a lot of RAM, and would probably outshine the others with a memory footprint so low it can scale very well on large-CPU low-RAM servers. It would easily win the "better" title by the 4th definition, "uses less resources", even if it ends up being slightly slower due to it.

Furthermore, those prefixes care only about what's in the present and may not carry the truth in their name in the future:
- This package could be abandoned, happens a lot in FOSS.
- This package could be replaced by another package. What would that package's name be? `best-canvas`?
- What if each runtime (Node.js included) start shipping a full spec compliant Canvas API that's more up to date and faster than this package? `better-canvas` would be inaccurate in that case if people consider "better" to be "faster".

At the end of the day, it's best to have packages a name which identify them, rather than giving it a biased subjective title. `@napi-rs/canvas` might not be the best name, but it tells us it's a Canvas API package, it's written in Rust, and makes use of NAPI-RS over node-gyp or CMake.js.

**Comment by Brooooooklyn** [comment]
Thank you @kyranet , you said what I wanted to say. The features of this package are not yet stable, and there are even many bugs.
