### ISSUE TITLE
Windows tests failed after `chrome/m117`

### ISSUE THREAD

**Issue by Brooooooklyn** [Brooooooklyn/canvas#761]
Tried to upgrade skia many times, but stuck by Windows tests failure: https://github.com/Brooooooklyn/canvas/actions/runs/7163033507/job/19501136477?pr=756

**Comment by CGQAQ** [comment]
https://paste.ubuntu.com/p/N53BhpVH8T/

I found that it's not skia version's issue, because:

I checkout main branch do:
1. cargo clean
2. yarn build && yarn test
10 tests failed.


if I run `node .\scripts\build-skia.js` and do the same steps
1. cargo clean
2. yarn build && yarn test
tests will all pass

Maybe someting related to the gn_args changes I guess?
